### PR TITLE
fix path encoding problems

### PR DESCRIPTION
**Pull request by AndersonBY**

### CODE REVIEW

**Comment by filmor** [comment]
Did you actually test this? Why should this work?

**Comment by AndersonBY** [comment]
Tested with two computers. One is set to utf8 encoding on Windows. One is default encoding. Both Windows are in Chinese. Default encoding on Chinese Windows is gbk. That's the problem causing error on path containing Chinese characters.

**Comment by filmor** [comment]
That's all fine, but the path is taken from a unicode string and passed to a function that decodes it from UTF8 again...

**Comment by AndersonBY** [comment]
Sorry I didn't dive deep into this. But it does fix my problems with Chinese characters in the path. I was using pywebview which deeps on pythonnet and it has some problems with Chinese characters' path. And the traceback points out here.

**Comment by link89** [comment]
Confirm that this patch does fix the issue: https://github.com/pythonnet/clr-loader/issues/59 
Hope to be included in the next release.

**Comment by link89** [comment]
Hi @filmor Do you have plan to accept this PR and make a new release?

**Comment by filmor** [comment]
Superceded by #62, sorry for the long delay and thank you for your effort :)

**Pull request closed without merging**
