### PR TITLE
Add support for mono_set_dirs

### LINKED ISSUE #27: Using a relocated Mono
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.9.2
-   Operating System: CentOS 7
-   .NET Runtime: 4.5

### Details

-   I relocated the `mono` I built from source (in preparation for embedding `mono` in a product) and got this

 ```
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `/opt/mono-6.8.0.123/lib/mono/4.5/mscorlib.dll' directory.
```
My understanding is `mono` can be relocated, but it requires invoking their C API to set the assembly paths, etc...
It would be nice if `clr-loader` could enable this by calling the right functions from `libmono-2.so`

I found this problem after relocating `mono` by running

`echo "import clr" | python3`

### PR DESCRIPTION
**Pull request by koubaa**
Fixes #27

### CODE REVIEW

**Comment by filmor** [comment]
Could you add a small test for this?

**Comment by koubaa** [comment]
@filmor sure!  Do I need to checkout & install an alternative mono binary for the test or could I just point it to system mono?

**Comment by filmor** [comment]
Just point at the system mono, I just want to be sure that the call itself succeeds.

**Comment by koubaa** [comment]
@filmor ok will do. I am setting up a docker image to see where the system mono usually is. I added another mono API `set_signal_chaining` and will test that too.

**Comment by koubaa** [comment]
@filmor tests added

**Comment by koubaa** [comment]
@filmor the test failures appear to be unrelated.  Do I need to edit any changelog?

**Comment by filmor** [comment]
I fixed the unrelated test failures. I don't keep a separate Changelog from the autogenerated ones from Github, I think that's fine for a repo of this size :)

Thank you for your contribution, I'll cut a release this week.

**Pull request merged**
